#custom build flags
warnFlags = ['-Wall', '-W']

#define build environment
env = Environment();
env.ParseConfig('fltk-config --cxxflags --ldflags');
warnEnv = env.Clone(CXXFLAGS=warnFlags);

warnEnv.Program(target='../../bin/gradar-config', source=Glob('src/*.cxx'));

