#SCONS build file

# create environment
env = Environment();

jarName='gradar-verify.jar';
installDir='../../../bin';

appClasses = env.Java('classes','com');
env.Jar(installDir+'/'+jarName, appClasses + ['com/MANIFEST.MF'] );
#env.Command(installDir+'/'+jarName, jarName, Copy("$TARGET", "$SOURCE"));
env.Clean('.', 'classes');
