#SCONS build file
import os;

# create environment
env = Environment();

# scons fails to properly pull inner classes into the jar files
# this seems to work
env['JARCHDIR']=os.path.join(env.Dir('.').get_abspath(),'classes')

jarName='../../../bin/gradar-verify.jar';

env.Java(target = 'classes', source = 'com',JAVAVERSION='1.6');

env.Jar(jarName, ['classes', 'com/MANIFEST.MF']);
env.Clean('.', 'classes');
