// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Status.proto

package gnuradar;

public final class Status {
  private Status() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StatusMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required int32 buffer_depth = 2;
    boolean hasBufferDepth();
    int getBufferDepth();
    
    // required int32 write_buffer = 3;
    boolean hasWriteBuffer();
    int getWriteBuffer();
    
    // required int32 read_buffer = 4;
    boolean hasReadBuffer();
    int getReadBuffer();
  }
  public static final class StatusMessage extends
      com.google.protobuf.GeneratedMessage
      implements StatusMessageOrBuilder {
    // Use StatusMessage.newBuilder() to construct.
    private StatusMessage(Builder builder) {
      super(builder);
    }
    private StatusMessage(boolean noInit) {}
    
    private static final StatusMessage defaultInstance;
    public static StatusMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public StatusMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gnuradar.Status.internal_static_gnuradar_StatusMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gnuradar.Status.internal_static_gnuradar_StatusMessage_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 buffer_depth = 2;
    public static final int BUFFER_DEPTH_FIELD_NUMBER = 2;
    private int bufferDepth_;
    public boolean hasBufferDepth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getBufferDepth() {
      return bufferDepth_;
    }
    
    // required int32 write_buffer = 3;
    public static final int WRITE_BUFFER_FIELD_NUMBER = 3;
    private int writeBuffer_;
    public boolean hasWriteBuffer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getWriteBuffer() {
      return writeBuffer_;
    }
    
    // required int32 read_buffer = 4;
    public static final int READ_BUFFER_FIELD_NUMBER = 4;
    private int readBuffer_;
    public boolean hasReadBuffer() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getReadBuffer() {
      return readBuffer_;
    }
    
    private void initFields() {
      name_ = "";
      bufferDepth_ = 0;
      writeBuffer_ = 0;
      readBuffer_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBufferDepth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWriteBuffer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReadBuffer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, bufferDepth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, writeBuffer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, readBuffer_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bufferDepth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, writeBuffer_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, readBuffer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static gnuradar.Status.StatusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gnuradar.Status.StatusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static gnuradar.Status.StatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static gnuradar.Status.StatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gnuradar.Status.StatusMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gnuradar.Status.StatusMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gnuradar.Status.internal_static_gnuradar_StatusMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gnuradar.Status.internal_static_gnuradar_StatusMessage_fieldAccessorTable;
      }
      
      // Construct using gnuradar.Status.StatusMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bufferDepth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        writeBuffer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        readBuffer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gnuradar.Status.StatusMessage.getDescriptor();
      }
      
      public gnuradar.Status.StatusMessage getDefaultInstanceForType() {
        return gnuradar.Status.StatusMessage.getDefaultInstance();
      }
      
      public gnuradar.Status.StatusMessage build() {
        gnuradar.Status.StatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private gnuradar.Status.StatusMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        gnuradar.Status.StatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public gnuradar.Status.StatusMessage buildPartial() {
        gnuradar.Status.StatusMessage result = new gnuradar.Status.StatusMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bufferDepth_ = bufferDepth_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.writeBuffer_ = writeBuffer_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.readBuffer_ = readBuffer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gnuradar.Status.StatusMessage) {
          return mergeFrom((gnuradar.Status.StatusMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(gnuradar.Status.StatusMessage other) {
        if (other == gnuradar.Status.StatusMessage.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasBufferDepth()) {
          setBufferDepth(other.getBufferDepth());
        }
        if (other.hasWriteBuffer()) {
          setWriteBuffer(other.getWriteBuffer());
        }
        if (other.hasReadBuffer()) {
          setReadBuffer(other.getReadBuffer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasBufferDepth()) {
          
          return false;
        }
        if (!hasWriteBuffer()) {
          
          return false;
        }
        if (!hasReadBuffer()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              bufferDepth_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              writeBuffer_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              readBuffer_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required int32 buffer_depth = 2;
      private int bufferDepth_ ;
      public boolean hasBufferDepth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getBufferDepth() {
        return bufferDepth_;
      }
      public Builder setBufferDepth(int value) {
        bitField0_ |= 0x00000002;
        bufferDepth_ = value;
        onChanged();
        return this;
      }
      public Builder clearBufferDepth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bufferDepth_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 write_buffer = 3;
      private int writeBuffer_ ;
      public boolean hasWriteBuffer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getWriteBuffer() {
        return writeBuffer_;
      }
      public Builder setWriteBuffer(int value) {
        bitField0_ |= 0x00000004;
        writeBuffer_ = value;
        onChanged();
        return this;
      }
      public Builder clearWriteBuffer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        writeBuffer_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 read_buffer = 4;
      private int readBuffer_ ;
      public boolean hasReadBuffer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getReadBuffer() {
        return readBuffer_;
      }
      public Builder setReadBuffer(int value) {
        bitField0_ |= 0x00000008;
        readBuffer_ = value;
        onChanged();
        return this;
      }
      public Builder clearReadBuffer() {
        bitField0_ = (bitField0_ & ~0x00000008);
        readBuffer_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:gnuradar.StatusMessage)
    }
    
    static {
      defaultInstance = new StatusMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:gnuradar.StatusMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gnuradar_StatusMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gnuradar_StatusMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Status.proto\022\010gnuradar\"^\n\rStatusMessag" +
      "e\022\014\n\004name\030\001 \002(\t\022\024\n\014buffer_depth\030\002 \002(\005\022\024\n" +
      "\014write_buffer\030\003 \002(\005\022\023\n\013read_buffer\030\004 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gnuradar_StatusMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gnuradar_StatusMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gnuradar_StatusMessage_descriptor,
              new java.lang.String[] { "Name", "BufferDepth", "WriteBuffer", "ReadBuffer", },
              gnuradar.Status.StatusMessage.class,
              gnuradar.Status.StatusMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
