#!/usr/bin/env python

import subprocess
import shutil

subprocess.call(['protoc','--cpp_out=cpp','Status.proto','Control.proto'])
subprocess.call(['protoc','--java_out=java','Status.proto','Control.proto' ])

shutil.move('cpp/Status.pb.h','../include/commands/Status.hpp')
shutil.move('cpp/Control.pb.h','../include/commands/Control.hpp')
shutil.move('cpp/Status.pb.cc','../programs/Run/Status.cxx')
shutil.move('cpp/Control.pb.cc','../programs/Run/Control.cxx')
shutil.move('java/gnuradar/Status.java','../programs/java/com/gnuradar/message/Status.java')
shutil.move('java/gnuradar/Control.java','../programs/java/com/gnuradar/message/Control.java')


