#custom build flags
flags = ['-Wall', '-W', '-DTIXML_USE_TICPP']

#setup library path and libraries
libPath=['/usr/lib','/usr/local/lib']
libs = ['tinyxmlcpp']

#define build environment
env = Environment(LIBS=libs, LIBPATH=libPath)
warnEnv = env.Clone(CXXFLAGS=flags)

warnEnv.Program(target='test', source='test.cpp')

