#custom build flags
flags = ['-g', '-Wall', '-W', '-DTIXML_USE_TICPP']

#setup libraries to link and paths
libs=['boost_system','boost_filesystem','tinyxmlcpp','pthread','usrp','usb','hdf5_hl_cpp','hdf5_cpp']
libPath=['/usr/lib','/usr/local/lib']

#define build environment
env = Environment()
warnEnv = env.Clone(LIBS=libs, LIBPATH=libPath, CXXFLAGS=flags)

prog1 = warnEnv.Program(target='../../bin/gradar-run-cli', 
   source=['GnuRadarRunCli.cxx','ProducerThread.cxx','ConsumerThread.cxx']);
prog2 = warnEnv.Program(target='../../bin/gradar-run-server',
   source=['GnuRadarRun.cxx','ProducerThread.cxx','ConsumerThread.cxx']);

warnEnv.Depends(prog1, Glob('../../include/*'))
warnEnv.Depends(prog2, Glob('../../include/*'))

