#custom build flags
warnFlags = ['-Wall', '-W']

#setup libraries to link and paths
libs=['rt','pthread','usrp','usb','hdf5_hl_cpp','hdf5_cpp']
libPath=['/usr/lib','/usr/local/lib']

#define build environment
env = Environment()
warnEnv = env.Clone(LIBS=libs, LIBPATH=libPath, CXXFLAGS=warnFlags)

#build target and install in root/bin directory
warnEnv.Program(target='../../bin/gradar-run', source=Glob('*.cxx'))

