#custom build flags
warnFlags = ['-Wall', '-W']

#define build environment
env = Environment();
warnEnv = env.Clone(CXXFLAGS=warnFlags);

warnEnv.Program(target='../../bin/gradar-verify', source='GnuRadarVerify.cxx', LIBS=['rt', 'pthread', 'usrp', 'usb']);
env.SConscript('java/SConscript');

