#custom build flags
warnFlags = ['-Wall', '-W']

#setup library path and libraries
libPath=['/usr/lib','/usr/local/lib']
libs = ['rt', 'pthread', 'usrp', 'usb']

#define build environment
env = Environment(LIBS=libs, LIBPATH=libPath)
warnEnv = env.Clone(CXXFLAGS=warnFlags)

warnEnv.Program(target='../../bin/gradar-verify', source='GnuRadarVerify.cxx')
env.SConscript('java/SConscript')

