#custom build flags
warnFlags = ['-Wall', '-W']

#define build environment
env = Environment();
warnEnv = env.Clone(CXXFLAGS=warnFlags);

libs=['rt','pthread','hdf5_hl_cpp','hdf5_cpp'];
warnEnv.Program(target='gradar-replay', source='GnuRadarReplay.cxx', LIBS=libs);

