#custom build flags
warnFlags = ['-Wall', '-W']

#setup library path
libPath=['/usr/lib','/usr/local/lib']

#define build environment
env = Environment(LIBPATH=libPath);
warnEnv = env.Clone(CXXFLAGS=warnFlags);

libs=['rt','pthread','hdf5_hl_cpp','hdf5_cpp'];
warnEnv.Program(target='../../bin/gradar-replay', source='GnuRadarReplay.cxx', LIBS=libs);

