#!/usr/bin/python

import os
import sys

#check for super-user
isRoot = False
if os.path.expandvars('$HOME') == '/root':
   isRoot = True

#1. verify super-user
#2. get include_path from user or use default
#3. if directory doesn't exist - create it.
#4. create links


if isRoot == False:
   print "Must be super user to install libraries"
else:
   os.chdir('../');
   root = os.getcwd();
   include_path = "/usr/local/lib";
   os.chdir(root + '/lib');
   os.system('cp libgrusrp.a ' + include_path);
   os.chdir(root);
   
