// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Status.proto

#ifndef PROTOBUF_Status_2eproto__INCLUDED
#define PROTOBUF_Status_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace gnuradar {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Status_2eproto();
void protobuf_AssignDesc_Status_2eproto();
void protobuf_ShutdownFile_Status_2eproto();

class StatusMessage;

// ===================================================================

class StatusMessage : public ::google::protobuf::Message {
 public:
  StatusMessage();
  virtual ~StatusMessage();
  
  StatusMessage(const StatusMessage& from);
  
  inline StatusMessage& operator=(const StatusMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const StatusMessage& default_instance();
  
  void Swap(StatusMessage* other);
  
  // implements Message ----------------------------------------------
  
  StatusMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StatusMessage& from);
  void MergeFrom(const StatusMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // required int32 buffer_depth = 2;
  inline bool has_buffer_depth() const;
  inline void clear_buffer_depth();
  static const int kBufferDepthFieldNumber = 2;
  inline ::google::protobuf::int32 buffer_depth() const;
  inline void set_buffer_depth(::google::protobuf::int32 value);
  
  // required int32 write_buffer = 3;
  inline bool has_write_buffer() const;
  inline void clear_write_buffer();
  static const int kWriteBufferFieldNumber = 3;
  inline ::google::protobuf::int32 write_buffer() const;
  inline void set_write_buffer(::google::protobuf::int32 value);
  
  // required int32 read_buffer = 4;
  inline bool has_read_buffer() const;
  inline void clear_read_buffer();
  static const int kReadBufferFieldNumber = 4;
  inline ::google::protobuf::int32 read_buffer() const;
  inline void set_read_buffer(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:gnuradar.StatusMessage)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_buffer_depth();
  inline void clear_has_buffer_depth();
  inline void set_has_write_buffer();
  inline void clear_has_write_buffer();
  inline void set_has_read_buffer();
  inline void clear_has_read_buffer();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::int32 buffer_depth_;
  ::google::protobuf::int32 write_buffer_;
  ::google::protobuf::int32 read_buffer_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_Status_2eproto();
  friend void protobuf_AssignDesc_Status_2eproto();
  friend void protobuf_ShutdownFile_Status_2eproto();
  
  void InitAsDefaultInstance();
  static StatusMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// StatusMessage

// required string name = 1;
inline bool StatusMessage::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StatusMessage::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StatusMessage::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StatusMessage::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& StatusMessage::name() const {
  return *name_;
}
inline void StatusMessage::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void StatusMessage::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void StatusMessage::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* StatusMessage::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* StatusMessage::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required int32 buffer_depth = 2;
inline bool StatusMessage::has_buffer_depth() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StatusMessage::set_has_buffer_depth() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StatusMessage::clear_has_buffer_depth() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StatusMessage::clear_buffer_depth() {
  buffer_depth_ = 0;
  clear_has_buffer_depth();
}
inline ::google::protobuf::int32 StatusMessage::buffer_depth() const {
  return buffer_depth_;
}
inline void StatusMessage::set_buffer_depth(::google::protobuf::int32 value) {
  set_has_buffer_depth();
  buffer_depth_ = value;
}

// required int32 write_buffer = 3;
inline bool StatusMessage::has_write_buffer() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StatusMessage::set_has_write_buffer() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StatusMessage::clear_has_write_buffer() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StatusMessage::clear_write_buffer() {
  write_buffer_ = 0;
  clear_has_write_buffer();
}
inline ::google::protobuf::int32 StatusMessage::write_buffer() const {
  return write_buffer_;
}
inline void StatusMessage::set_write_buffer(::google::protobuf::int32 value) {
  set_has_write_buffer();
  write_buffer_ = value;
}

// required int32 read_buffer = 4;
inline bool StatusMessage::has_read_buffer() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StatusMessage::set_has_read_buffer() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StatusMessage::clear_has_read_buffer() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StatusMessage::clear_read_buffer() {
  read_buffer_ = 0;
  clear_has_read_buffer();
}
inline ::google::protobuf::int32 StatusMessage::read_buffer() const {
  return read_buffer_;
}
inline void StatusMessage::set_read_buffer(::google::protobuf::int32 value) {
  set_has_read_buffer();
  read_buffer_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gnuradar

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Status_2eproto__INCLUDED
